dip/views/auth.py
from flask import Blueprint, make_response, render_template, request, url_for, current_app, redirect, g
from sqlalchemy import text
import re

from dip.utils.session import get_current_user, create_session
from dip.utils.session import set_user_identity, SESSION_COOKIE_NAME
from dip.utils.security import generate_password_hash
from dip.models import User
from dip.extensions import db


bp = Blueprint('bp_auth', __name__)


@bp.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'GET':

        user = get_current_user()

        if not user:
            return render_template('login.html')

        return redirect(url_for('bp_user.profile'))

    if request.method == 'POST':
        username = request.form['username']
        plain_password = request.form['password']
        pattern = "[^a-zA-Zа-яА-Я0-9?!#$%@]"

        #
        username = username.replace("'", "")
        username = re.sub(pattern, "", username)
        plain_password = plain_password.replace("'", "")
        #

        hashed_password = generate_password_hash(
            plain_password, current_app.config['PASSWORD_SALT'])

        user_query = db.session.query(User).filter(
            text(f"username='{username}' AND password='{hashed_password}'"))

        conn = db.engine.raw_connection()
        cur = conn.cursor()
        cur.execute(str(user_query))
        user = cur.fetchone()

        if not user:
            return render_template('login.html', error='Неверный логин или пароль'), 403

        user = dict(zip([
            'id',
            'first_name',
            'second_name',
            'patronymic',
            'username',
            'photo',
            'email',
            'password',
            'phone_number',
            'job_title',
            'role',
        ], user))

        if not user:
            return render_template('login.html', error='Неверный логин или пароль'), 403

        session = create_session(user['username'], user['role'])

        resp = redirect(url_for('bp_user.profile'))
        resp.set_cookie(SESSION_COOKIE_NAME, session)

        g.user = user

        return resp


@bp.route('/logout', methods=['GET'])
def logout():
    resp = make_response(redirect(url_for('bp_auth.login')))
    resp.delete_cookie(SESSION_COOKIE_NAME)
    return resp

dip/views/index.py
from flask import Blueprint, render_template, g



bp = Blueprint('bp_index', __name__)


@bp.route('/', methods=['GET'])
def index():
    return render_template('index.html')

dip/templates/components/admin_sidebar.html
<div class="sidebar">
    <ul class="sidebar__list">
      <li class="sidebar__item"><a href="{{ url_for('bp_admin.users') }}" class="sidebar__link">Пользователи</a></li>
      <li class="sidebar__item"><a href="{{ url_for('bp_admin.job_titles') }}" class="sidebar__link">Должности</a></li>
    </ul>
</div>

{% block scripts %}
    <script src="{{ url_for('static', filename='js/admin_dashboard.js') }}"></script>
{% endblock %}

dip/templates/components/navbar.html
<header>
    <nav class="navbar">
        <h1 class="navbar__logo"><a class="navbar__menu-item-link" href="{{ url_for('bp_index.index') }}">DORA FOND</a></h1>
        <ul class="navbar__menu">
            {% if g['user'] %}
            <li class="navbar__menu-item">
                <a class="navbar__menu-item-link" href="{{ url_for('bp_user.profile') }}">Профиль</a>
            </li>

            <li class="navbar__menu-item">
                <a class="navbar__menu-item-link" href="{{ url_for('bp_wiki.wiki') }}">База знаний</a>
            </li>

            {% if g['user']['role'] == 'admin' %}
            <li class="navbar__menu-item {% if 'admin/dashboard' in request.path %} navbar__menu-item-active {% endif %}">
                <a class="navbar__menu-item-link" href="{{ url_for('bp_admin.users') }}">Управление</a>
            </li>
            {% endif %}
            <li class="navbar__menu-item">
                <a class="navbar__menu-item-link" href="{{ url_for('bp_auth.logout') }}">Выход</a>
            </li>
            {% endif %}
            {% if not g['user'] %}
            <li class="navbar__menu-item">
                <a class="navbar__menu-item-link" href="{{ url_for('bp_auth.login') }}">Войти</a>
            </li>
            {% endif %}
        </ul>
    </nav>
</header>

{% block script %}
    <script src="{{ url_for('static', filename='js/navbar.js') }}"></script>
{% endblock %}