dip/views/users.py
from flask import Blueprint, make_response, render_template, request, url_for, current_app, redirect

from dip.utils.session import set_user_identity, authed_only, get_current_user, role_required, set_user_if_authed
from dip.utils.security import remove_image_metadata, generate_password_hash
from dip.extensions import db
from dip.models import User

bp = Blueprint('bp_user', __name__)

MAGIC_NUMBERS = { 'png': bytes([0x89, 0x50, 0x4E, 0x47, 0x0D, 0x0A, 0x1A, 0x0A]),
                  'jpg': bytes([0xFF, 0xD8, 0xFF, 0xE0]),
                  'jpeg': bytes([0xFF, 0xD8, 0xFF, 0xDB]),
                  'jpeg-jfif': bytes([0xFF, 0xD8, 0xFF, 0xE0, 0x00, 0x10, 0x4A, 0x46, 0x49, 0x46, 0x00, 0x01]),
                  'jpeg1': bytes([0xFF, 0xD8, 0xFF, 0xEE]),
                }

bp.before_app_request(set_user_if_authed)
bp.after_app_request(set_user_identity)


@bp.route('/profile', methods=['GET', 'POST'])
@authed_only
def profile():

    if request.method == 'GET':

        current_user = get_current_user()
        user_json = current_user.json()

        if user_json.get('photo'):
            user_json['photo'] = url_for(
                'static.send_user_image', id_=current_user.id)

        else:
            user_json['photo'] = url_for(
                'static', filename='img/profile-picture.jpg')

        return render_template('profile.html', user=user_json)

    else:
        current_user = get_current_user()
        user_json = current_user.json()

        user_data = request.form

        photo_file = request.files.get('photo')

        if photo_file.filename:
            filepath = current_app.config['PATHS']['user_images'] / \
                photo_file.filename

            if not filepath.exists():
                max_read_size = max(len(m) for m in MAGIC_NUMBERS.values())
                file_head = photo_file.read(max_read_size)

                flag = 0
                for ext in MAGIC_NUMBERS:
                    print(file_head.startswith(MAGIC_NUMBERS[ext]), file_head, MAGIC_NUMBERS[ext])
                    if file_head.startswith(MAGIC_NUMBERS[ext]):
                        photo_file.save(filepath)
                        with open(filepath, 'rb') as file:
                            content = file.read()

                        with open(filepath, 'wb') as file:
                            file.write(file_head)
                            file.write(content)

                        remove_image_metadata(photo_file.filename)
                        flag += 1
                        break

                if not flag:
                    return f'Нельзя загружать файлы данного типа', 403

            current_user.photo = photo_file.filename

        if user_data.get('password'):
            current_user.password = generate_password_hash(user_data.get(
                'password'), current_app.config['PASSWORD_SALT'])

        db.session.commit()

        return redirect(url_for('bp_user.profile'))

@bp.route('/profile/<username>', methods=['GET', 'POST'])
@role_required(['user', 'admin'])
def profile_username(username):
    if request.method == 'GET':

        user = User.query.filter_by(username=username).first()

        user_json = user.json()

        if user_json.get('photo'):
            user_json['photo'] = url_for(
                'static.send_user_image', id_=user.id)

        else:
            user_json['photo'] = url_for(
                'static', filename='img/profile-picture.jpg')

        return render_template('profile_id.html', user=user_json)

dip/views/wiki.py
from flask import Blueprint, make_response, render_template, request, url_for, current_app, redirect, render_template_string
from sqlalchemy import desc
from slugify import slugify
import re

from dip.utils.session import authed_only, get_current_user
from dip.extensions import db
from dip.models import WikiPage

bp = Blueprint('bp_wiki', __name__)


@bp.route('/wiki', methods=['GET', 'POST'])
@authed_only
def wiki():

    wiki_pages = WikiPage.query.order_by(desc(WikiPage.created_at)).all()

    return render_template('wiki.html', wiki_pages=wiki_pages)


@bp.route('/wiki/<slug>', methods=['GET'])
@authed_only
def wiki_slug(slug):
    wiki_page = WikiPage.query.filter_by(slug=slug).first()

    if not wiki_page:
        return render_template('404.html'), 404

    return render_template_string(render_template('wiki_slug.html', wiki_page=wiki_page.json()))


@bp.route('/wiki/create', methods=['GET', 'POST'])
@authed_only
def wiki_create():
    pattern = "[^a-zA-Zа-яА-Я0-9.,;:#!?()\\s\\n]"

    if request.method == 'GET':
        return render_template('wiki_create.html')

    wiki_data = request.form

    title = wiki_data.get('title')
    title = title.replace("'", "")
    title = title.replace('"', "")
    title = re.sub(pattern, "", title)

    if not title:
        return render_template('wiki_create.html', error='Не указан заголовок'), 400

    title_exists = WikiPage.query.filter_by(name=title).first()

    if title_exists:
        return render_template('wiki_create.html', error='Запись с таким именем уже существует'), 400

    content = wiki_data.get('content').replace("{", "")
    content = content.replace("}", "")
    content = content.replace("'", "")
    content = content.replace('"', "")
    content = re.sub(pattern, "", content)

    slug = slugify(title)
    slug = slug.replace("'", "")
    slug = slug.replace('"', "")
    slug = re.sub(pattern, "", slug)

    current_user = get_current_user()

    wiki_page = WikiPage(
        name=title,
        slug=slug,
        content=content,
        owner_id=current_user.id,
    )

    db.session.add(wiki_page)
    db.session.commit()

    return redirect(url_for('bp_wiki.wiki'))

dip/templates/admin_dashboard.html
{% extends "base.html" %}

{% block content %}

<div class="container-sidebar">
    {% include "components/admin_sidebar.html" %}

    <div class="container">
        <h1>Панель управления администратора</h1>

        {% block admin_content %}
        {% endblock %}
    </div>

</div>

{% endblock %}

dip/templates/admin_dashboard_job_titles.html
{% extends "admin_dashboard.html" %}

{% block admin_content %}

<div class="job-titles-list">
    <h1 class="job-titles-list__title">Должности</h1>

    {% if not job_titles %}
        <div class="job-titles-list__message job-titles-list__message-info">
            Пока еще нет созданных должностей
        </div>
    {% else %}

        <ul class="job-titles-list__items">
        {% for jt in job_titles %}

                <li class="job-titles-list__item" id="{{ jt['id'] }}">
                    <span class="job-titles-list__name" contenteditable="true">{{ jt['title'] }}</span>
                    <button class="job-titles-list__button job-titles-list__button--delete">Delete</button>
                </li>

        {% endfor %}
        </ul>

    {% endif %}

    {% if error %}

        <div class="job-titles-list__message job-titles-list__message-error">
            {{ error }}
        </div>

    {% endif %}

        <form class="job-titles-list__form" method="POST">
            <div class="job-titles-list__form__group">
                <label class="job-titles-list__form__label" for="username">Название должности:</label>
                <input class="job-titles-list__form__input" type="text" name="job_title" id="job_title">
            </div>
            <button type="submit" class="job-titles-list__button job-titles-list__button--submit">Добавить</button>
        </form>

        <div class="job-titles-list__temp-message job-titles-list__temp-message-error"></div>
    </div>

{% endblock %}

{% block scripts %}
    <script src="{{ url_for('static', filename='js/admin_dashboard_jobs.js') }}"></script>
{% endblock %}

dip/templates/admin_dashboard_users.html
{% extends "admin_dashboard.html" %}

{% block admin_content %}

<div class="user-list">
    <h1 class="user-list__title">User List</h1>
    <div class="user-list__action-add">
        <button class="user-list__button user-list__button--add">Добавить <i class="bi bi-plus"></i></button>
    </div>
    <table class="user-list__table">
        <thead>
            <tr>
                <th>Username</th>
                <th>ФИО</th>
                <th>Должность</th>
                <th>Email</th>
                <th>Роль</th>
                <th>Действия</th>
            </tr>
        </thead>
        <tbody>

            {% for user in users %}

            {% if user['role'] == 'admin' %}

            <tr class="user-list__item" id="{{ user['id'] }}">
                <td class="user-list__field">{{ user['username'] }}</td>
                <td class="user-list__field">Скрыто</td>
                <td class="user-list__field">Скрыто</td>
                <td class="user-list__field">{{ user['email'] }}</td>
                <td class="user-list__field">{{ user['role'] }}</td>
                <td class="user-list__actions">
                    <button class="user-list__button user-list__button--edit"><i class="bi bi-pencil"></i></button>
                    <button class="user-list__button user-list__button--delete"><i class="bi bi-trash"></i></button>
                </td>
            </tr>

            {% else %}

            <tr class="user-list__item" id="{{ user['id'] }}">
                <td class="user-list__field">{{ user['username'] }}</td>
                <td class="user-list__field">{{ user['second_name'] + ' ' + user['first_name'] + ' ' +
                    user['patronymic'] }}</td>
                <td class="user-list__field">{{ user['job_title']['title'] }}</td>
                <td class="user-list__field">{{ user['email'] }}</td>
                <td class="user-list__field">{{ user['role'] }}</td>
                <td class="user-list__actions">
                    <button class="user-list__button user-list__button--edit"><i class="bi bi-pencil"></i></button>
                    <button class="user-list__button user-list__button--delete"><i class="bi bi-trash"></i></button>
                </td>
            </tr>

            {% endif %}

            {% endfor %}

        </tbody>
    </table>
    <div class="job-titles-list__temp-message job-titles-list__temp-message-error"></div>
</div>

<div class="modal">
    <div class="modal__overlay"></div>
    <div class="modal__content">
        <h2 class="modal__title">Edit User</h2>
        <form id="edit-user-form" class="modal__form" method="POST" enctype="multipart/form-data">
            <input type="hidden" name="id">
            <div class="modal__form__group">
                <label class="modal__form__label" for="username">Username:</label>
                <input class="modal__form__input" type="text" name="username" id="username">
            </div>
            <div class="modal__form__group">
                <label class="modal__form__label" for="first_name">Имя:</label>
                <input class="modal__form__input" type="text" name="first_name" id="first_name">
            </div>
            <div class="modal__form__group">
                <label class="modal__form__label" for="second_name">Фамилия:</label>
                <input class="modal__form__input" type="text" name="second_name" id="second_name">
            </div>
            <div class="modal__form__group">
                <label class="modal__form__label" for="patronymic">Отчество:</label>
                <input class="modal__form__input" type="text" name="patronymic" id="patronymic">
            </div>
            <div class="modal__form__group">

                <div class="modal__form__group">
                    <label class="modal__form__label" for="job_title">Должность:</label>
                    <select class="modal__form__select" name="job_title" id="job_title">
                        {% for jt in job_titles %}
                        <option value="{{ jt['id'] }}">{{ jt['title'] }}</option>
                        {% endfor %}
                    </select>
                </div>
            </div>
            <div class="modal__form__group">
                <label class="modal__form__label" for="email">Email:</label>
                <input class="modal__form__input" type="email" name="email" id="email">
            </div>
            <div class="modal__form__group">
                <label class="modal__form__label" for="phone_number">Номер телефона:</label>
                <input class="modal__form__input" type="tel" pattern="(\+7|7|8)[0-9]{10}" name="phone_number" id="phone_number">
            </div>
            <div class="modal__form__group">
                <label class="modal__form__label" for="photo">Фото:</label>
                <img class="user-card__img" src="{{ url_for('static', filename='img/profile-picture.jpg') }}" alt="Profile picture" id="photo_preview">
                <input type="file" id="photo" accept="image/*" style="display:none;" name="photo">
            </div>
            <div class="modal__form__group">
                <label class="modal__form__label" for="role">Роль:</label>
                <select class="modal__form__select" name="role" id="role">
                    {% for role in roles %}
                    <option value="{{ role }}">{{ role }}</option>
                    {% endfor %}
                </select>
            </div>
            <div class="modal__form__group">
                <label class="modal__form__label" for="password">Пароль:</label>
                <input class="modal__form__input" type="password" name="password" id="password" autocomplete="on">
            </div>
            <div class="message message-error"></div>
            <div class="modal__form__actions">
                <button type="submit" class="modal__button modal__button--submit">Save</button>
                <button type="button" class="modal__button modal__button--cancel">Cancel</button>
            </div>
        </form>
    </div>
</div>
{% endblock %}

{% block scripts %}
<script src="{{ url_for('static', filename='js/admin_dashboard_users.js') }}"></script>
{% endblock %}

dip/templates/base.html
<!DOCTYPE html>
<html>
    <head>
        <title>DORA FOND</title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">

        <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='layout.css') }}">
        <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='elements.css') }}">
        <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='forms.css') }}">
        <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='lists.css') }}">
        
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@300;400;600&display=swap" rel="stylesheet">

        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css">
    </head>

    <body>
        {% include "components/navbar.html" %}

        <main>
            {% block content %}
            {% endblock %}
        </main>

        <footer class="footer">
            <div class="footer__content">
                <p>&copy; DevSecOps 2023, МИИГАиК</p>
            </div>
        </footer> 

        {% block scripts %}
        {% endblock %}
    </body>

</html>

dip/templates/index.html
{% extends "base.html" %}

{% block content %}

<div class="wave">
    <div class="text">DORA FOND - это благотварительный фонд, который отправляет все собранные на концертах средства на
        помощь в продвижении малоизвестных исполнителей. Мы делаем музыку и мир лучше!</div>
</div>

{% endblock %}

dip/templates/login.html
{% extends "base.html" %}

{% block content %}

<div class="container">

    <form class="login-form" method="POST">
        <h1 class="login-form__header">Добро пожаловать!</h1>
        {% if error %}
        <div class="login-form__message-error">
            <p class="login-form__message-error__text">{{ error }}</p>
        </div>
        {% endif %}
        <label class="login-form__label" for="username">Username</label>
        <input class="login-form__input" type="text" id="username" name="username" required>
        <label class="login-form__label" for="password">Password</label>
        <input class="login-form__input" type="password" id="password" name="password" required>
        <input class="login-form__button" type="submit" value="Войти">
      </form>

</div>

{% endblock %}

dip/templates/profile.html
{% extends "base.html" %}

{% block content %}

<div class="container">
  <h1>Карточка пользователя</h1>


  <div class="user-card">
    <img class="user-card__img" src="{{ user['photo'] }}" alt="Profile picture">
    <h2 class="user-card__field-bold">{{ user['full_name'] }}</h2>
    <p class="user-card__field">{{ user['job_title']['title'] }}</p>
    <p class="user-card__field">{{ user['email'] }}</p>
    <p class="user-card__field">{{ user['phone_number'] }}</p>
    <button class="user-card__button">Редактировать</a>
  </div>


  <div class="modal">
    <div class="modal__overlay"></div>
    <div class="modal__content">
        <h2 class="modal__title">Сменить фото</h2>
        <form id="edit-user-form" class="modal__form" method="POST" enctype="multipart/form-data">
            <input type="hidden" name="id">
            <div class="modal__form__group">
                <label class="modal__form__label" for="photo">Фото:</label>
                <img class="user-card__img" src="{{ url_for('static', filename='img/profile-picture.jpg') }}" alt="Profile picture" id="photo_preview">
                <input type="file" id="photo" accept="image/*" style="display:none;" name="photo">
            </div>
            <div class="modal__form__group">
                <label class="modal__form__label" for="password">Пароль:</label>
                <input class="modal__form__input" type="password" name="password" id="password" autocomplete="on">
            </div>
            <div class="message message-error"></div>
            <div class="modal__form__actions">
                <button type="submit" class="modal__button modal__button--submit">Сохранить</button>
                <button type="button" class="modal__button modal__button--cancel">Отмена</button>
            </div>
        </form>
    </div>
</div>


</div>

{% endblock %}

{% block scripts %}
<script src="{{ url_for('static', filename='js/user_profile.js') }}"></script>
{% endblock %}

dip/templates/profile_edit.html
{% extends "base.html" %}

{% block content %}

<div class="edit-profile-form">
    <h2>Edit Profile</h2>
    <form>
      <label for="name">Name:</label>
      <input type="text" id="name" name="name" value="John Doe">
      
      <label for="email">Email:</label>
      <input type="email" id="email" name="email" value="john.doe@example.com">
      
      <label for="job-title">Job Title:</label>
      <input type="text" id="job-title" name="job-title" value="Web Developer">
      
      <label for="bio">Bio:</label>
      <textarea id="bio" name="bio">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</textarea>
      
      <button type="submit">Save</button>
    </form>
  </div>

{% endblock %}

dip/templates/profile_id.html
{% extends "base.html" %}

{% block content %}

<div class="container">
  <h1>Карточка пользователя</h1>


  <div class="user-card">
    <img class="user-card__img" src="{{ user['photo'] }}" alt="Profile picture">
    <h2 class="user-card__field-bold">{{ user['full_name'] }}</h2>
    <p class="user-card__field">{{ user['job_title']['title'] }}</p>
    <p class="user-card__field">{{ user['email'] }}</p>
    <p class="user-card__field">{{ user['phone_number'] }}</p>
  </div>

</div>

{% endblock %}

{% block scripts %}
<script src="{{ url_for('static', filename='js/user_profile.js') }}"></script>
{% endblock %}

dip/templates/wiki.html
{% extends "base.html" %}

{% block content %}

<div class="container">
    <h1>База знаний</h1>

    <div class="button-container button-container-right">
        <a class="button button--add" href="{{ url_for('bp_wiki.wiki_create') }}">Добавить <i class="bi bi-plus"></i></a>
    </div>

    {% if not wiki_pages %}
    <div class="message message-info">
        Пока нет записей в базе знаний. Ты можешь быть первым!
    </div>
    {% else %}
        <div class="wiki">
            {% for page in wiki_pages %}
                <div class="wiki__item">
                    <h2 class="wiki__item__title"><a href="{{ url_for('bp_wiki.wiki_slug', slug=page['slug']) }}">{{ page['name'] }}</a></h2>
                    <div class="wiki__item__meta">
                        <a class="wiki__item__author" href="{{ url_for('bp_user.profile_username', username=page['owner']['username']) }}">{{ page['owner']['username'] }}</a>
                        <p class="wiki__item__date">{{ page['created_at'] }}</p>
                    </div>
                </div>
            {% endfor %}
        </div>
    {% endif %}



</div>

{% endblock %}

{% block scripts %}
{% endblock %}

dip/templates/wiki_create.html
{% extends "base.html" %}

{% block content %}

<div class="container">
    <h1>Создание страницы базы знаний</h1>

    <form class="form form-large" method="POST" enctype="multipart/form-data">
        <div class="form__group">
            <label class="form__label" for="title">Заголовок:</label>
            <input class="form__input" type="text" name="title" id="title">
        </div>
        <div class="form__group">
            <label class="form__label" for="content">Содержимое в markdown:</label>
            <textarea class="form__input form__input-textarea" name="content" id="content"></textarea>
        </div>
        {% if error %}
            <div class="message message-error">{{ error }}</div>
        {% endif %}
        <div class="button-container button-container-right">
            <button type="submit" class="button button--submit">Сохранить</button>
        </div>
    </form>


</div>

{% endblock %}

{% block scripts %}
{% endblock %}

dip/templates/wiki_slug.html
{% extends "base.html" %}

{% block content %}

<div class="container">
    <h1>{{ wiki_page['name'] }}</h1>

    <div class="wiki">
        <div class="wiki__item__meta">
            <a class="wiki__item__author" href="{{ url_for('bp_user.profile_username', username=wiki_page['owner']['username']) }}">{{ wiki_page['owner']['username'] }}</a>
            <p class="wiki__item__date">{{ wiki_page['created_at'] }}</p>
        </div>
        <div class="wiki__item">
            {{ wiki_page['html']|safe }}
        </div>
    </div>

</div>

{% endblock %}

{% block scripts %}
{% endblock %}